### ISSUE TITLE
BUG(docker_compose_project): Nulls appearing in docker networks.

### ISSUE THREAD

**Issue by zloveless** [zloveless/ansible-containers#7]
Offending task: https://github.com/zloveless/ansible-containers/blob/main/roles/docker_compose_project/tasks/install.yaml#L24-L28

I'm wondering if it's `to_nice_yaml` being weird. it's taking the following valid docker compose file piece
```yaml
networks:
  default:
  backend:
  web:
    external: true
  cloudflare:
    external: true
```
and writing this
```yaml
networks:
  default: null
  backend: null
  web:
    external: true
  cloudflare:
    external: true
```
I've tried replacing the blanks with `{}` just emits `{}` as written.

It's breaking when the systemd service is starting.
